apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec:
  selector:
    matchLabels:
      color: blue
  replicas: 1
  template:
    metadata:
      labels:
        color: blue
    spec:
      containers:
      - name: blue
        image: 192.168.8.100:5000/web:blue
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blue-lb
spec:
  ports:
    - name: blue-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    color: blue
  type: LoadBalancer
